# Generated by Django 3.1.1 on 2020-10-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201009_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='atime',
            new_name='time',
        ),
    ]
